version: '3.1'

services:
  db:
    image: mysql
    container_name: cubes-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - persisted-data:/var/lib/mysql
      - ./import_db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3336:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links: 
      - db

  backend:
    image: arichard76/cubes-api:latest
    restart: always
    ports:
      - 8000:8000
    links:
      - db

volumes:
  persisted-data: