name: Docker build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-docker-and-deploy:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v2.4.0
      with:
        context: .
        pull: true
        tags: latest
